# Generated by Django 4.2.4 on 2023-08-06 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_remove_settings_distribution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='distribution_time_finish',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 22, 22, 53, 911799), verbose_name='дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_time_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='дата начала рассылки'),
        ),
    ]
