# Generated by Django 4.2.4 on 2023-08-17 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='distribution_time_finish',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='distribution_time_start',
        ),
        migrations.AddField(
            model_name='settings',
            name='distribution_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='время рассылки'),
        ),
    ]
