# Generated by Django 4.2.4 on 2023-08-17 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_alter_settings_distribution_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='distribution_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 17, 20, 49, 19, 907491, tzinfo=datetime.timezone.utc), null=True, verbose_name='время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 17, 20, 49, 19, 907491, tzinfo=datetime.timezone.utc), null=True, verbose_name='время окончания рассылки'),
        ),
    ]
