# Generated by Django 4.2.4 on 2023-08-17 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_alter_settings_distribution_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='distribution_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_stop_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время окончания рассылки'),
        ),
    ]
