# Generated by Django 4.2.4 on 2023-08-06 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='time_interval',
            field=models.CharField(default=datetime.timedelta(days=1), max_length=150, verbose_name='периодичность'),
        ),
    ]
