# Generated by Django 4.2.4 on 2023-08-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_interval_time_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='message',
            name='settings',
        ),
        migrations.AddField(
            model_name='logs',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distribution.message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distribution.message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interval',
            name='time_interval',
            field=models.CharField(max_length=150, verbose_name='периодичность'),
        ),
    ]
