# Generated by Django 4.2.4 on 2023-09-25 10:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'verbose_name': 'Distribution Interval', 'verbose_name_plural': 'Distribution Intervals'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': 'Distribution Log', 'verbose_name_plural': 'Distribution Logs'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('set_published', 'Can Publish')], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Distribution Setting', 'verbose_name_plural': 'Distribution Settings'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Distribution Status', 'verbose_name_plural': 'Distribution Statuses'},
        ),
        migrations.AlterField(
            model_name='interval',
            name='time_interval',
            field=models.CharField(max_length=150, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_attempt_response',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Last Attempt Response'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_attempt_status',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Last Attempt Status'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_attempt_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Attempt Time'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Message Owner'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='Message Subject'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Message Body'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.interval', verbose_name='Distribution Periodicity'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Distribution Start Time'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.status', verbose_name='Distribution Status'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_stop_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Distribution Stop Time'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Distribution Time'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=150, verbose_name='Status'),
        ),
    ]
