# Generated by Django 4.2.4 on 2023-08-06 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_remove_message_logs_remove_message_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='distribution_time',
        ),
        migrations.AddField(
            model_name='settings',
            name='distribution_time_finish',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 22, 20, 46, 714367), verbose_name='время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='settings',
            name='distribution_time_start',
            field=models.DateField(default=datetime.datetime.now, verbose_name='время начала рассылки'),
        ),
    ]
