# Generated by Django 4.2.4 on 2023-08-08 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_settings_distribution_time_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_time_finish',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 17, 5, 10, 611467), verbose_name='дата окончания рассылки'),
        ),
    ]
