# Generated by Django 4.2.4 on 2023-08-17 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_settings_distribution_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='distribution_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='distribution_stop_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='время окончания рассылки'),
        ),
    ]
